// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddServiceAccount(arg1:string):Promise<string>;

export function CheckConflict(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Record<string, any>>;

export function CopyNode(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:boolean,arg10:boolean):Promise<Record<string, any>>;

export function CreateAuthUser(arg1:string,arg2:string,arg3:Record<string, any>):Promise<Record<string, any>>;

export function DeleteAuthUser(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteDocument(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function GetAccounts():Promise<Array<main.Account>>;

export function GetDocument(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function ListAuthUsers(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string):Promise<main.AuthUsersResponse>;

export function ListDocuments(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string):Promise<Record<string, any>>;

export function ListProjects(arg1:string):Promise<Array<main.Project>>;

export function ListRootCollections(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function RunJSScript(arg1:string,arg2:string,arg3:string,arg4:string):Promise<any>;

export function RunSimpleQuery(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>):Promise<any>;

export function SaveDocument(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Record<string, any>,arg6:boolean):Promise<Record<string, any>>;

export function UpdateAuthUser(arg1:string,arg2:string,arg3:Record<string, any>):Promise<Record<string, any>>;
