// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServiceAccount(arg1) {
  return window['go']['main']['App']['AddServiceAccount'](arg1);
}

export function CheckConflict(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CheckConflict'](arg1, arg2, arg3, arg4, arg5);
}

export function CopyNode(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['CopyNode'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function CreateAuthUser(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateAuthUser'](arg1, arg2, arg3);
}

export function DeleteAuthUser(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteAuthUser'](arg1, arg2, arg3);
}

export function DeleteDocument(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DeleteDocument'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetDocument(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetDocument'](arg1, arg2, arg3, arg4);
}

export function ListAuthUsers(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ListAuthUsers'](arg1, arg2, arg3, arg4, arg5);
}

export function ListDocuments(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ListDocuments'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ListProjects(arg1) {
  return window['go']['main']['App']['ListProjects'](arg1);
}

export function ListRootCollections(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListRootCollections'](arg1, arg2, arg3);
}

export function RunJSScript(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunJSScript'](arg1, arg2, arg3, arg4);
}

export function RunSimpleQuery(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunSimpleQuery'](arg1, arg2, arg3, arg4);
}

export function SaveDocument(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveDocument'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateAuthUser(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateAuthUser'](arg1, arg2, arg3);
}
